export const SkillNames = {
    FirearmsHeavy: 'Firearms - Heavy',
    FirearmsLong: 'Firearms - Long',
    FirearmsSmall: 'Firearms - Small',
    Grenades: 'Grenades',
    Gunnery: 'Gunnery',
    MartialArts: 'Martial Arts',
    MeleeWeapons: 'Melee Weapons',
    Astrogation: 'Astrogation',
    Chemistry: 'Chemistry',
    Computers: 'Computers',
    Cultures: 'Cultures',
    Engineering: 'Engineering',
    Medicine: 'Medicine',
    StarshipPiloting: 'Starship Piloting',
    Acrobatics: 'Acrobatics',
    AircraftPilot: 'Aircraft Pilot',
    AnimalHandling: 'Animal Handling',
    Athletics: 'Athletics',
    Deflection: 'Deflection',
    GroundVehicles: 'Ground Vehicles',
    Survival: 'Survival',
    Awareness: 'Awareness',
    Bureaucracy: 'Bureaucracy',
    Evasion: 'Evasion',
    Interrogation: 'Interrogation',
    Stealth: 'Stealth',
    Streetsmarts: 'Streetsmarts',
    Trading: 'Trading',
} as const;
export type SkillName = (typeof SkillNames)[keyof typeof SkillNames];
